# Generated by Django 4.0.5 on 2022-07-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimregister',
            name='state_local',
            field=models.CharField(choices=[('RC', 'Recibido'), ('AS', 'Asignado'), ('EE', 'En ejecución'), ('CP', 'Completado')], default='AS', max_length=15, verbose_name='Estado'),
        ),
    ]
