# Generated by Django 4.0.5 on 2022-07-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0002_alter_claimregister_state_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='image',
            field=models.ImageField(null=True, upload_to='tipos_reclamos', verbose_name='imagen representativa'),
        ),
    ]
