# Generated by Django 4.0.5 on 2022-07-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(null=True, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=30, null=True, unique=True, verbose_name='calle')),
            ],
            options={
                'verbose_name': 'calle',
                'verbose_name_plural': 'calles',
            },
        ),
    ]
