# Generated by Django 4.0.3 on 2022-05-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='document_number',
        ),
        migrations.AddField(
            model_name='user',
            name='cuil_cuim',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CUIM/CUIL'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='celular'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='teléfono'),
        ),
    ]
