# Generated by Django 4.0.3 on 2022-05-14 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0054_remove_claimregister_image_remove_noteclaim_image_and_more'),
        ('users', '0002_remove_user_document_number_user_cuil_cuim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_reason_type', to='claim.type', verbose_name='tipo de reclamo'),
        ),
    ]
